export * from './aadhaar';
export * from './credit-card';
export * from './email';
export * from './file-extension';
export * from './ip';
export * from './hex-color';
export * from './postal-zip';
export * from './ssn';
export * from './url';
